import type { Metadata } from "next";
import { Manrope, Inter } from "next/font/google";
import "./globals.css";
import "./container.css";
import Header from "@/components/Header/Header";
import TanStackQueryProvider from "@/components/TanStackQueryProvider/TanStackQueryProvider";
import { Toaster } from "react-hot-toast";

const manrope = Manrope({
  variable: "--font-family",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${manrope.variable} ${inter.variable}`}>
      <TanStackQueryProvider>
        <body>
          <Header />
          {children}
          <Toaster />
        </body>
      </TanStackQueryProvider>
    </html>
  );
}
